services:
  app:
    build: .
    container_name: app_tp
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel
  webserver:
    image: nginx:latest
    container_name: nginx_server_tp
    ports:
      - "8197:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: mysql_db_tp
    ports:
      - "9669:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel
  db_test:
    image: mysql:8.0
    container_name: mysql_db_test
    restart: always
    environment:
      MYSQL_DATABASE: laravel_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel_test
      MYSQL_PASSWORD: laravel_test
    ports:
      - "3320:3306"
    networks:
      - laravel
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
networks:
  laravel:
    driver: bridge
volumes:
  minio-data:
