services:
  app:
    build: .
    container_name: app_tp
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel
  webserver:
    image: nginx:latest
    container_name: nginx_server_tp
    ports:
      - "8194:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: mysql_db_tp
    ports:
      - "9667:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel
  db_test:
    image: mysql:8.0
    container_name: mysql_db_test
    restart: always
    environment:
      MYSQL_DATABASE: laravel_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel_test
      MYSQL_PASSWORD: laravel_test
    ports:
      - "3317:3306"
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
